[[tasks]]
type = "Fight"

# 活动
[[tasks.variants]]
params = { stage = "EA-8" }
condition = { type = "DateTime", start = "2023-08-01T16:00:00", end = "2025-03-21T03:59:59" }

# 日常
[[tasks.variants]]
condition = { type = "Weekday", weekdays = ["Mon"]}
params = { stage = "AP-5" }

[[tasks.variants]]
condition = { type = "Weekday", weekdays = ["Tue"]}
params = { stage = "PR-D-2" }

[[tasks.variants]]
condition = { type = "Weekday", weekdays = ["Wed"]}
params = { stage = "PR-C-2" }

[[tasks.variants]]
condition = { type = "Weekday", weekdays = [ "Thu"]}
params = { stage = "PR-A-2" }

[[tasks.variants]]
condition = { type = "Weekday", weekdays = [ "Fri"]}
params = { stage = "PR-B-2" }

[[tasks.variants]]
condition = { type = "Weekday", weekdays = [ "Sat","Sun"]}
params = { stage = "AP-5" }
