[[tasks]]
type = "Fight"
strategy = "first" # 或者 "first" (默认)

# 在周天晚上使用所有的将要过期的理智药
[[tasks.variants]]
params = { expiring_medicine = 0 }

[tasks.variants.condition]
type = "And"
conditions = [
  { type = "Time", start = "18:00:00" },
  { type = "Weekday", weekdays = ["Sun"] },
]

# 活动
[[tasks.variants]]
params = { stage = "EA-8" }
condition = { type = "DateTime", start = "2023-08-01T16:00:00", end = "2025-03-21T03:59:59" }

# 日常
[[tasks.variants]]
condition = { type = "Weekday", weekdays = ["Mon", "Thu", "Sat", "Sun"]}
params = { stage = "AP-5" }

# 日常
[[tasks.variants]]
condition = { type = "Weekday", weekdays = ["Tue"]}
params = { stage = "CE-6" }

# 日常
[[tasks.variants]]
condition = { type = "Weekday", weekdays = ["Wed","Fri"]}
params = { stage = "CA-5" }

# 其他时间，刷1-7
# [[tasks.variants]]
# params = { stage = "1-7" }
