services:
  maa-cli:
    image: crestfallmax/maa-cli:v0.3
    environment:
      - http_proxy=http://192.168.3.40:8892
      - https_proxy=http://192.168.3.40:8892
    volumes:
      - ./app:/app

  arknights:
    privileged: true
    ports:
        - 5755:5555
    # image: cnflysky/redroid-rk3588:12.0.0-latest
    image: redroid/redroid:11.0.0-latest
    command:
        - androidboot.redroid_gpu_mode=host

